name: 02 - Workflow Events
on: 
    schedule:
        - cron: '25 * * * *'
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{ github.event_name }}"