name: 13 - Using Cache

on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                required: false
                description: "Whether to execute cache step"
            node-version:
                type: choice
                options: ['20.x','19.x','18.x']
                default: '20.x'
                description: "Node version to be executed"
                required: false

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./13-caching/react-app
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to non prod
              run: |-
                echo "Deploying to non-prod"