name: 15 - Working with Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{ matrix.os }} - ${{ matrix.node }}
        strategy:
            fail-fast: false
            matrix:
                node: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node: 16.x
                    - tag: experimental
                      os: ubuntu-latest
                      node: 21.x
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: Fail if experimental
              if: ${{ matrix.tag == 'experimental' }}
              run: exit 1
            - name: Perform some tests
              run: |-
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
                sleep 10
            - name: Upload test results
              run: |-
                echo "Uploading test results"
            