name: 16 - Working with Environments

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            my-env-value: ${{ vars.TARGET_VAR == null && inputs.target-env.default || vars.TARGET_VAR }}
        steps:
            - name: Echo vars
              run: |- 
                echo "Env variable: ${{ env.my-env-value }}"