name : 17 - 1 - Custom Actions - Composite

run-name: 17 - 1 -Custom Actions - Composite | env - ${{ inputs.target-env }}

env:
    working-directory: 17-custom-actions/react-app

on:
    workflow_dispatch:
        inputs:
            target-env:
                required: false
                default: dev
                type: choice
                options: [dev, prod]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Setup Node and NPM dependencies
              id: install_dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 20.x
                working-dir: ./17-custom-actions/react-app
                target-env: ${{ inputs.target-env }}
            - name: Print dependencies setup output
              run: echo ${{ steps.install_dependencies.outputs.installed-deps }}
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build