name: 17 - 2 - Custom Actions - JS

on:
    workflow_dispatch:
        inputs:
            base-branch:
                required: true
                default: main
            target-branch:
                required: false
                default: update/npm-dependencies
            working-dir:
                required: true
                default: ./17-custom-actions/react-app
            debug:
                type: boolean
                required: false
                default: false

run-name: 17 - 2 - Custom Actions - JS | Base ${{ inputs.base-branch }} | Target ${{ inputs.target-branch }} | Directory ${{ inputs.working-dir }}

permissions:
    contents: write
    pull-requests: write

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Check for dependency updates
              id: updates
              uses: ./.github/actions/js-dependency-update
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.working-dir }}
                gh-token: ${{ secrets.GITHUB_TOKEN }}
                debug: ${{ inputs.debug }}
            - name: Print updates available
              run: echo ${{ steps.updates.outputs.updates-available && 'There are updates available' || 'No updates available at the moment' }}