name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://madeupurl.com'
        description: url to ping
        required: true
        default: 'https://ww.google.com'
      max_trials:
        description: max number of tries until action fails
        required: false
        default: '10'
      delay:
        description: time between requests to url
        default: '5'
        required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        id: ping_url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
      - name: Print url reachable value
        run: echo ${{ steps.ping_url.outputs.url-reachable && 'Url is reachable' || 'Url not reachable'}}
