name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: url to ping
        required: true
        default: 'https://ww.google.com'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}