name: 18 - 2 - Reusable Workflows

on: 
    workflow_dispatch:
        inputs:
            target-directory:
                default: './17-custom-actions'
                required: true

jobs:
    reuse_workflow:
        uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
            target-directory: ${{ inputs.target-directory }}
    
    print_outputs:
        runs-on: ubuntu-latest
        needs: 
            - reuse_workflow
        steps:
            - name: Print Outputs
              run: |
                echo 'Workflow caller printer'
                echo 'build-status: ${{ needs.reuse_workflow.outputs.build-status }}'
                echo 'url: ${{ needs.reuse_workflow.outputs.url }}'
            
